### ISSUE TITLE
[Bug] Can't run the website locally.

### ISSUE THREAD

**Issue by 0xSileo** [l2beat/l2beat#3086]
I followed [the steps from the Contributing.md guidelines ](https://github.com/l2beat/l2beat/blob/main/CONTRIBUTING.md#running-the-website-locally), and used [NVM](https://github.com/nvm-sh/nvm) to swicth to node v18.0.0. 

Everything ran fine until `yarn start`, where I get a whole lot-of 

```bash
issues: [
    { code: 'custom', message: 'Invalid input', path: [Array] },
    { code: 'custom', message: 'Invalid input', path: [Array] },
    { code: 'custom', message: 'Invalid input', path: [Array] },
    { code: 'custom', message: 'Invalid input', path: [Array] },
...
```
errors, as well as :

```bash
[15:01:25] 'buildContent' errored after 2.51 s
[15:01:25] Error: 1
    at formatError (/home/sileo/Github/l2beat/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/home/sileo/Github/l2beat/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:539:35)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/home/sileo/Github/l2beat/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/sileo/Github/l2beat/node_modules/now-and-later/lib/map.js:50:14)
    at f (/home/sileo/Github/l2beat/node_modules/once/once.js:25:25)
    at f (/home/sileo/Github/l2beat/node_modules/once/once.js:25:25)
    at tryCatch (/home/sileo/Github/l2beat/node_modules/async-done/index.js:24:15)
    at done (/home/sileo/Github/l2beat/node_modules/async-done/index.js:40:12)
[15:01:25] 'watch' errored after 2.51 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I use arch btw.

**Comment by torztomasz** [comment]
Do you have your main branch synced to the top? If so, have you run [these](https://github.com/l2beat/l2beat/blob/main/CONTRIBUTING.md#running-the-website-locally) commands?

**Comment by 0xSileo** [comment]
Yes, I had just cloned the repo, and per my previous comment, executed [the commands written CONTRIBUTING.md file](https://github.com/l2beat/l2beat/blob/main/CONTRIBUTING.md#running-the-website-locally). 
Anyway, got it to work now, not sure what caused it but I did `git pull` then repeated the commands once more and now it's running fine.
